[package]
name = "flowex-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
config.workspace = true
serde.workspace = true
dotenvy.workspace = true
anyhow.workspace = true
